force-app/main/default/objects/Deposit__c/Deposit__c.object-meta.xml
<CustomObject>
    <label>Deposit</label>
    <nameField>
        <label>Deposit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deposits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deposit__c/fields/Bank_Country_Raw__c.field-meta.xml
<CustomField>
    <fullName>Bank_Country_Raw__c</fullName>
    <label>Bank Country Raw</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CPQDepositAccessorTest.cls
@isTest
private class CPQDepositAccessorTest {

    @isTest static void testIsXMLEntryValid_invalidUSEntry(){
        //setup
        CPQDepositAccessor validator = new CPQDepositAccessor();
        Deposit__c testDeposit = new Deposit__c(Bank_Country_Raw__c = 'US');
        String entryCode = '115';
        
        //test
        Boolean isValid = validator.isXMLEntryValid(testDeposit, entryCode);
        
        //expect
        System.assert(isValid == false);
    }
    
    @isTest static void testIsXMLEntryValid_invalidCADEntry(){
        //setup
        CPQDepositAccessor validator = new CPQDepositAccessor();
        Deposit__c testDeposit = new Deposit__c(Bank_Country_Raw__c = 'CA');
        String entryCode = '115';
        
        //test
        Boolean isValid = validator.isXMLEntryValid(testDeposit, entryCode);
        
        //expect
        System.assert(isValid == false);
    }
    
    @isTest static void testIsXMLEntryValid_invalidGBEntry(){
        //setup
        CPQDepositAccessor validator = new CPQDepositAccessor();
        Deposit__c testDeposit = new Deposit__c(Bank_Country_Raw__c = 'GB');
        String entryCode = '115';
        
        //test
        Boolean isValid = validator.isXMLEntryValid(testDeposit, entryCode);
        
        //expect
        System.assert(isValid == false);
    }
    
    @isTest static void testIsXMLEntryValid_ValidCountry(){
        //setup
        CPQDepositAccessor validator = new CPQDepositAccessor();
        Deposit__c testDeposit = new Deposit__c(Bank_Country_Raw__c = 'MX');
        String entryCode = '115';
        
        //test
        Boolean isValid = validator.isXMLEntryValid(testDeposit, entryCode);
        
        //expect
        System.assert(isValid == true);
    }
    

    
    
}