force-app/main/default/objects/Deposit__c/Deposit__c.object-meta.xml
<CustomObject>
    <label>Deposit</label>
    <nameField>
        <label>Deposit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deposits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deposit__c/fields/Bank_Batch_Reference__c.field-meta.xml
<CustomField>
    <fullName>Bank_Batch_Reference__c</fullName>
    <label>Bank Batch Reference</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/Bank_Batch_Type__c.field-meta.xml
<CustomField>
    <fullName>Bank_Batch_Type__c</fullName>
    <label>Bank Batch Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/Bank_Country_Raw__c.field-meta.xml
<CustomField>
    <fullName>Bank_Country_Raw__c</fullName>
    <label>Bank Country Raw</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/Bank_Raw__c.field-meta.xml
<CustomField>
    <fullName>Bank_Raw__c</fullName>
    <label>Bank Raw</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/Check_Num__c.field-meta.xml
<CustomField>
    <fullName>Check_Num__c</fullName>
    <label>Check Num</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/Postmark_Date__c.field-meta.xml
<CustomField>
    <fullName>Postmark_Date__c</fullName>
    <label>Postmark Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Matched</fullName>
            </value>
            <value>
                <fullName>Mystery Payment</fullName>
            </value>
            <value>
                <fullName>Not Matched</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payload__c/Payload__c.object-meta.xml
<CustomObject>
    <label>Payload</label>
    <nameField>
        <label>Payload Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payloads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CPQCalCSVParserTest.cls
@isTest
private class CPQCalCSVParserTest {
    
    @isTest static void testParsePayloadCSVStringPositive(){
        //setup
        CPQCalCSVParser parser = new CPQCalCSVParser();
        Payload__c p = CPQPayloadDataFactoryTest.createSingleEntryPayload_CAL();
        List<Deposit__c> dList;

        //test
        Test.startTest();
        dList = parser.parsePayloadCSVString(p);
        Test.stopTest();

        //expect
        System.assertEquals(1, parser.csv.size());
        System.assertEquals(1, parser.finalDepositList.size());
        System.assertEquals(1, dList.size());
    }
    
    @isTest static void testParsePayloadCSVStringNoDeposits(){
        //setup
        CPQCalCSVParser parser = new CPQCalCSVParser();
        Payload__c p = CPQPayloadDataFactoryTest.createNoEntryPayload_CAL();
        List<Deposit__c> dList;

        //test
        Test.startTest();
        dList = parser.parsePayloadCSVString(p);
        Test.stopTest();

        //expect
        System.assertEquals(0, parser.csv.size());
        System.assertEquals(0, parser.finalDepositList.size());
        System.assertEquals(0, dList.size());
    }
    
    @isTest static void convertCALrowToDepositPositive(){
        CPQCalCSVParser parser = new CPQCalCSVParser();
        String rowString = '1,1,1,G-3009001,G-3009001,TA300958a20201000001,CAL-310390,2020/04/13,11:00,1,1,Check,,,$1254.40,07040-010,4827813,002621,3,9,,1,1b,9,,,,531088 B C LTD,2020/03/31,2-1128441329,$1254.40,BALLAST HOLDINGS';
        String payloadName = 'CAL-310390_20200413111931.zip';
        Date importDate = Date.newInstance(2020, 4, 13);
        Date postmarkDate = Date.newInstance(2020, 3, 31);
        
        Test.startTest();
        parser.convertCALrowToDeposit(rowString, payloadName);
        Test.stopTest();

        System.assert(parser.currDeposit.Name == 'TA300958a20201000001');
        System.assert(parser.currDeposit.Status__c == 'Open');
        System.assert(parser.currDeposit.Bank_Batch_Reference__c == payloadName);
        System.assert(parser.currDeposit.Bank_Batch_Type__c == 'Check');
        System.assert(parser.currDeposit.Bank_Raw__c == 'BoA : CAD');
        System.assert(parser.currDeposit.Bank_Country_Raw__c == 'CA');
        System.assert(parser.currDeposit.Check_Num__c == '002621');
        System.assert(parser.currDeposit.CurrencyIsoCode == 'CAD');
        System.assert(parser.currDeposit.Import_Date__c == importDate); 
        System.assert(parser.currDeposit.Postmark_Date__c == postmarkDate); 
    }
    
    @isTest static void testConvertCALrowToDepositHandlesInvalidAmount(){
        //setup
        CPQCalCSVParser parser = new CPQCalCSVParser();
        String rowString = '1,1,1,G-3009001,G-3009001,TA300958a20201000001,CAL-310390,2020/04/13,11:00,1,1,Check,,,$invalid,07040-010,4827813,002621,3,9,,1,1b,9,,,,531088 B C LTD,2020/03/31,2-1128441329,$invalid,BALLAST HOLDINGS';
        String payloadName = 'CAL-310390_20200413111931.zip';
        
        //test
        try{
       		Deposit__c d = parser.convertCALrowToDeposit(rowString, payloadName);
        //expect
        }catch(Exception e){
            String exceptionType = e.getTypeName();
            System.debug(exceptionType);
            System.assert(exceptionType == 'CPQCalCSVParser.CPQCALParsingInvalidAmountException');
        }
    }
    
    @isTest static void testConvertCALrowToDepositHandlesInvalidDate(){
        //setup
        CPQCalCSVParser parser = new CPQCalCSVParser();
        String rowString = '1,1,1,G-3009001,G-3009001,TA300958a20201000001,CAL-310390,invalidD,11:00,1,1,Check,,,$1254.40,07040-010,4827813,002621,3,9,,1,1b,9,,,,531088 B C LTD,2020/03/31,2-1128441329,$1254.40,BALLAST HOLDINGS';
        String payloadName = 'CAL-310390_20200413111931.zip';
        
        //test
        try{
       		Deposit__c d = parser.convertCALrowToDeposit(rowString, payloadName);
        //expect
        }catch(Exception e){
            String exceptionType = e.getTypeName();
            System.debug(exceptionType);
            System.assert(exceptionType == 'CPQCalCSVParser.CPQCALParsingInvalidDateException');
        }
    }
    
        
    
    

}