force-app/main/default/objects/Deposit__c/Deposit__c.object-meta.xml
<CustomObject>
    <label>Deposit</label>
    <nameField>
        <label>Deposit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deposits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deposit__c/fields/Bank_Batch_Reference__c.field-meta.xml
<CustomField>
    <fullName>Bank_Batch_Reference__c</fullName>
    <label>Bank Batch Reference</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/Bank_Batch_Type__c.field-meta.xml
<CustomField>
    <fullName>Bank_Batch_Type__c</fullName>
    <label>Bank Batch Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/Bank_Country_Raw__c.field-meta.xml
<CustomField>
    <fullName>Bank_Country_Raw__c</fullName>
    <label>Bank Country Raw</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/Bank_Raw__c.field-meta.xml
<CustomField>
    <fullName>Bank_Raw__c</fullName>
    <label>Bank Raw</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/Bank_Reference__c.field-meta.xml
<CustomField>
    <fullName>Bank_Reference__c</fullName>
    <label>Bank Reference</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/Postmark_Date__c.field-meta.xml
<CustomField>
    <fullName>Postmark_Date__c</fullName>
    <label>Postmark Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Matched</fullName>
            </value>
            <value>
                <fullName>Mystery Payment</fullName>
            </value>
            <value>
                <fullName>Not Matched</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payload__c/Payload__c.object-meta.xml
<CustomObject>
    <label>Payload</label>
    <nameField>
        <label>Payload Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payloads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CPQCamt052XMLParserTest.cls
@isTest
private class CPQCamt052XMLParserTest {
    
    @isTest static void testParsePatternCAMT052Positive(){
        //setup
        CPQCamt052XMLParser camt052 = new CPQCamt052XMLParser();
        Payload__c camt052Payload = CPQPayloadDataFactoryTest.createSingleEntryPayload_CAMT052();
        List<Deposit__c> createdDeposits = new List<Deposit__c>();
        Datetime importDate = DateTime.newInstanceGmt(2020, 4, 30, 12, 7, 41);
        Date postmarkDate = Date.newInstance(2020, 4, 30);
        
        //test
        Test.startTest();
        createdDeposits = camt052.parsePatternCAMT052(camt052Payload);
        Test.stopTest();

        //expect
        System.assertEquals(1,camt052.CAMT052_deposits.size());
        System.assert(camt052.currDeposit.Name == '6008121DA902');
        System.assert(camt052.currDeposit.Bank_Reference__c == '6008121DA902');
        System.assert(camt052.currDeposit.CurrencyIsoCode == 'USD');
        System.assert(camt052.currDeposit.Amount__c == 5750.00);
        System.assert(camt052.currDeposit.Bank_Raw__c == 'Bank of America, London');
        System.assert(camt052.currDeposit.Bank_Country_Raw__c == 'GB');
        System.assert(camt052.currDeposit.Status__c == 'Open');
        System.assert(camt052.currDeposit.Bank_Batch_Reference__c == camt052Payload.Name);
        System.assert(camt052.currDeposit.Bank_Batch_Type__c == 'Transfer');   
        System.assert(camt052.currDeposit.Import_Date__c == importDate);
        System.assert(camt052.currDeposit.Postmark_Date__c == postmarkDate);  
    }
    
    @isTest static void testParsePatternCAMT052HandleInvalidDates(){
        //setup
        CPQCamt052XMLParser camt052 = new CPQCamt052XMLParser();
        Payload__c camt052Payload = CPQPayloadDataFactoryTest.createInvalidDatePayload_CAMT052();
        List<Deposit__c> createdDeposits = new List<Deposit__c>();
        
        //test
        try{
        	createdDeposits = camt052.parsePatternCAMT052(camt052Payload);  
        //expect
        }catch(Exception e){
            String exceptionType = e.getTypeName();
            System.debug(exceptionType);
            System.assert(exceptionType == 'CPQCamt052XMLParser.CPQInvalidXML052StringToDateException');
        }
    }
    
    @isTest static void testParsePatternCAMT052HandleInvalidAmount(){
        //setup
        CPQCamt052XMLParser camt052 = new CPQCamt052XMLParser();
        Payload__c camt052Payload = CPQPayloadDataFactoryTest.createInvalidAmountPayload_CAMT052();
        List<Deposit__c> createdDeposits = new List<Deposit__c>();
        String errorMsg;
        
        //test
        try{
        	createdDeposits = camt052.parsePatternCAMT052(camt052Payload);
        //expect
        }catch(Exception e){
            String exceptionType = e.getTypeName();
            System.debug(exceptionType);
            System.assert(exceptionType == 'CPQCamt052XMLParser.CPQInvalidXML052StringToNumberException');
        }
    }
    
    
    

}