force-app/main/default/objects/Deposit__c/Deposit__c.object-meta.xml
<CustomObject>
    <label>Deposit</label>
    <nameField>
        <label>Deposit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deposits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deposit__c/fields/Bank_Batch_Reference__c.field-meta.xml
<CustomField>
    <fullName>Bank_Batch_Reference__c</fullName>
    <label>Bank Batch Reference</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/Bank_Batch_Type__c.field-meta.xml
<CustomField>
    <fullName>Bank_Batch_Type__c</fullName>
    <label>Bank Batch Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/Bank_Country_Raw__c.field-meta.xml
<CustomField>
    <fullName>Bank_Country_Raw__c</fullName>
    <label>Bank Country Raw</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/Bank_Raw__c.field-meta.xml
<CustomField>
    <fullName>Bank_Raw__c</fullName>
    <label>Bank Raw</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/Bank_Reference__c.field-meta.xml
<CustomField>
    <fullName>Bank_Reference__c</fullName>
    <label>Bank Reference</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/Postmark_Date__c.field-meta.xml
<CustomField>
    <fullName>Postmark_Date__c</fullName>
    <label>Postmark Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Matched</fullName>
            </value>
            <value>
                <fullName>Mystery Payment</fullName>
            </value>
            <value>
                <fullName>Not Matched</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payload__c/Payload__c.object-meta.xml
<CustomObject>
    <label>Payload</label>
    <nameField>
        <label>Payload Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payloads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CPQCamt054XMLParserTest.cls
@isTest
private class CPQCamt054XMLParserTest {
    
    @isTest static void testParsePatternCAMT054Positive(){
        //setup
        CPQCamt054XMLParser camt054 = new CPQCamt054XMLParser();
        Payload__c camt054Payload = CPQXMLDataFactoryTest.createSingleEntryPayload_CAMT054();
        List<Deposit__c> createdDeposits = new List<Deposit__c>();
        Datetime importDate = DateTime.newInstanceGmt(2020, 4, 30, 10, 42, 45);
        Date postmarkDate = Date.newInstance(2020, 4, 30);
        
        //test
        Test.startTest();
        createdDeposits = camt054.parsePatternCAMT054(camt054Payload);
        Test.stopTest();

        //expect
        System.assertEquals(1,camt054.CAMT054_deposits.size());
        System.assert(camt054.currDeposit.Name == '2000003852USX1');
        System.assert(camt054.currDeposit.Bank_Reference__c == '2000003852USX1');
        System.assert(camt054.currDeposit.CurrencyIsoCode == 'USD');
        System.assert(camt054.currDeposit.Amount__c == 3400);
        System.assert(camt054.currDeposit.Bank_Raw__c == 'USABA111000025');
        System.assert(camt054.currDeposit.Bank_Country_Raw__c == 'US');
        System.assert(camt054.currDeposit.Status__c == 'Open');
        System.assert(camt054.currDeposit.Bank_Batch_Reference__c == camt054Payload.Name);
        System.assert(camt054.currDeposit.Bank_Batch_Type__c == 'ACH/LOW VALUE - CTX');   
        System.assert(camt054.currDeposit.Import_Date__c == importDate);
        System.assert(camt054.currDeposit.Postmark_Date__c == postmarkDate);      
    }
    
    @isTest static void testParsePatternCAMT054HandleInvalidDates(){
        //setup
        CPQCamt054XMLParser camt054 = new CPQCamt054XMLParser();
        Payload__c camt054Payload = CPQXMLDataFactoryTest.createInvalidDatePayload_CAMT054();
        List<Deposit__c> createdDeposits = new List<Deposit__c>();
        String errorMsg;
        
        //test

        try{
        	createdDeposits = camt054.parsePatternCAMT054(camt054Payload);
        //expect
        }catch(Exception e){
            String exceptionType = e.getTypeName();
            System.debug(exceptionType);
            System.assert(exceptionType == 'CPQCamt054XMLParser.CPQInvalidXML054StringToDateException');
        }
    }
    
    @isTest static void testParsePatternCAMT054HandleInvalidAmount(){
        //setup
        CPQCamt054XMLParser camt054 = new CPQCamt054XMLParser();
        Payload__c camt054Payload = CPQXMLDataFactoryTest.createInvalidAmountPayload_CAMT054();
        List<Deposit__c> createdDeposits = new List<Deposit__c>();
        String errorMsg;
        
        //test
   
        try{
        	createdDeposits = camt054.parsePatternCAMT054(camt054Payload);
        //expect
        }catch(Exception e){
            String exceptionType = e.getTypeName();
            System.debug(exceptionType);
            System.assert(exceptionType == 'CPQCamt054XMLParser.CPQInvalidXML054StringToNumberException');
        }
    }
    
    
    

}